version: '3.8'

services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.1.3
    container_name: keycloak-dev
    ports:
      - "8080:8080"
    environment:
      KC_DB: dev-file
      KC_HTTP_ENABLED: "true"
      KC_HEALTH_ENABLED: "true"
      KC_METRICS_ENABLED: "true"
      KC_FEATURES: scripts
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
    command: ["start-dev"]
    restart: unless-stopped
    networks:
      - pointer-network

  pointer-back:
    build: .
    container_name: pointer-back
    ports:
      - "8082:8082"
    env_file:
      - .env
    restart: unless-stopped
    depends_on:
      - keycloak
    networks:
      - pointer-network

  pointer-front:
    build: ../tcs-pointer-front
    container_name: pointer-front
    ports:
      - "80:80"
    env_file:
      - .env
    restart: unless-stopped
    depends_on:
      - pointer-back
    networks:
      - pointer-network

networks:
  pointer-network:
    driver: bridge
